apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Parser       docker
        Tag          kube.*

    [OUTPUT]
        Name         http
        Match        *
        Host         host.minikube.internal
        Port         8088
        URI          /services/collector
        Header       Authorization Bearer d62afe83-7eb6-4363-be7a-d154d13b8570
        Format       json
        tls          On
        tls.verify   Off
  parsers.conf: |
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
